---
database:
  host: localhost
  user: agent
  name: camunda
  password: password
  port: 5432
  ssl_mode: disable
  batchSize: 100
kassette-server:
  url: http://localhost:8080
  batchSize: 10
kassette-agent:
  uid: camunda


