---
database:
  host: localhost
  user: postgres
  name: postgres
  password: mysecretpassword
  port: 5432
  ssl_mode: disable
  batch_size: 100
kassette-server:
  url: http://localhost:8088/extract
  batch_size: 10
kassette-agent:
  uid: camunda
tables:
  act_hi_actinst:
    track_column: start_time_
    id_column: id_
  act_hi_detail:
    track_column: time_
    id_column: id_


