version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5430:5432  
    environment:
      POSTGRES_USER: kassette_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kassette
  postgres-warehouse:
    image: postgres:latest
    restart: always
    ports:
      - 5429:5432  
    environment:
      POSTGRES_USER: kassette_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse

  kassette-server:
    image: golang:1.20.4
    command: bash -c "cd /opt/kassette-ai/ && find . -name go.sum -o -name go.mod -delete && rm -f kassette-server && go mod init kassette.ai/kassette-server && go mod tidy && go build && chmod 0755 kassette-server && ./kassette-server"
    depends_on:
      - postgres
      - postgres-warehouse
    ports:
      - 8088:8088
    volumes:
      - .:/opt/kassette-ai/    

