services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432  
    environment:
      POSTGRES_USER: kassette_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kassette
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U kassette_user -d workflow'"]
      interval: 10s
      timeout: 3s
      retries: 3    
  kassette-server:
    image: metaops/kassette-server:v1.1.1
    restart: always
    ports:
      - 8088:8088
    volumes: 
      - ./config.yaml:/opt/kassette-ai/config.yaml
    depends_on:
      postgres:
        condition: service_healthy

  kassette-transformer:
    image: metaops/kassette-transformer:dev_v1.1.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      kassette-server:
        condition: service_started
