---
database:
  host: postgres
  user: camundadiy
  name: workflow
  password: camundadiy
  port: 5432
  ssl_mode: disable
  batchSize: 100
kassette-server:
  url: http://kassette-server:8088
  batchSize: 10
kassette-agent:
  customerName: Camunda_Customer
  secretKey: w1U3za00hhl57mB4dfn1696109930187
