name: Agent deploy into Kubernetes

on: ['deployment', 'workflow_dispatch' ]

jobs:
  agent-deployment:
    runs-on: self-hosted  
    steps:
    - name: 'Agent Deploy'
      uses: 'azure/setup-helm@v3'
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
      id: install
    - name: add metaops helm repo
      run: helm repo add metaops https://metaops-solutions.github.io/helm-charts
    - name: install release
      run: helm upgrade -i --wait --timeout 5m -n kassette-dev kassette-agent metaops/kassette-agent --set config.database.user=camundadiy,config.database.password=camundadiy,config.database.host=postgres-postgresql-hl.camunda-diy.svc,config.database.name=workflow,config.kassette-server.url='http://kassette-server.kassette-dev.svc/extract'

