name: deploy into Kubernetes

on: ['deployment', 'workflow_dispatch' ]

jobs:
  deployment:
    runs-on: self-hosted  
    steps:
    - name: 'Deploy'
      uses: 'azure/setup-helm@v3'
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
      id: install
    - name: add metaops helm repo
      run: helm repo add metaops https://metaops-solutions.github.io/helm-charts
    - name: upgrade -i --wait --timeout 5m -n kassette-dev kassette-server metaops/kassette-server

