name: deploy into Kubernetes

on: ['deployment', 'workflow_dispatch' ]

jobs:
  deployment:
    runs-on: self-hosted  
    steps:
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with: 
        namespace: 'kassette-dev'
        chart: 'metaops/kassette-server'
        repo: 'https://metaops-solutions.github.io/helm-charts'
        repo-alias: 'metaops'
        release: 'kassette-server'
        token: '${{ github.token }}'

