name: Go compile

on:
  push:
    branches: [ "main", "andrey" ]
  pull_request:
    branches: [ "main", "andrey" ]

env:
  AGENT_IMAGE_NAME: metaops/kassette-agent
  SERVER_IMAGE_NAME: metaops/kassette-server


jobs:
  build:
    runs-on: self-hosted  

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4
    - run: go version

    - name: cleanup the build files if any
      run: find . -name go.sum -o -name go.mod -delete

    - name: cleanup the build artefacts if any
      run: rm -f kassette-server connections/kassete-agent

    - name: Build kassette-server
      run: go mod init kassette.ai/kassette-server && go mod tidy && go build

    - name: Build docker image for kassete-server
      run:  docker build . --file Dockerfile --tag ${{ env.SERVER_IMAGE_NAME }}:latest

    - name: Build kassette-agent
      run: cd connections && go mod init kassette.ai/kassete-agent && go mod tidy && go build

    - name: Build docker image for kassete-agent
      run:  cd connections && docker build . --file Dockerfile --tag ${{ env.AGENT_IMAGE_NAME }}:latest

    - name: docker login
      if: github.event_name != 'pull_request'
      run: docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD

    - name: docker push agent
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.AGENT_IMAGE_NAME }}:latest

    - name: docker push server
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.SERVER_IMAGE_NAME }}:latest


