name: Go compile

on:
  push:
    branches: [ "main", "andrey" ]
  pull_request:
    branches: [ "main", "andrey" ]

env:
  IMAGE_NAME: metaops/kassette-server


jobs:
  build:
    runs-on: self-hosted  

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4
    - run: go version

    - name: cleanup the build files if any
      run: find . -name go.sum -o -name go.mod -delete

    - name: cleanup the build artefacts if any
      run: rm -f kassette-server 

    - name: Build kassette-server
      run: go mod init kassette.ai/kassette-server && go mod tidy && go build

