name: Go compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: metaops/kassette-server


jobs:
  build:
    runs-on: self-hosted  

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

    - name: Build
        run: go build -mod=mod main.go

    - name: docker build
      run:  docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest

    - name: docker login
      if: github.event_name != 'pull_request'
      run: docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD

    - name: docker push
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.IMAGE_NAME }}:latest

